# This file was generated by GoReleaser. DO NOT EDIT.
cask "afm" do
  version "0.5.43"

  on_macos do
    on_intel do
      sha256 "624064f78b46aaea4a6906297befed720966e847acac91e7bdcf7bede5440432"
      url "https://github.com/akopichin/afm/releases/download/v#{version}/afm_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "01007b8449f3e1073cb4a4f254dfa5bb87adf75f2cefb1b71930f4492e41d9e2"
      url "https://github.com/akopichin/afm/releases/download/v#{version}/afm_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2de6cfc7b401194bbd512a26b14e5bf470fdb6761c6ac5d72dca0717774ca9ad"
      url "https://github.com/akopichin/afm/releases/download/v#{version}/afm_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b03cf67477642455a13ffc01a601585a71d149169e24e4ee363d2a1de8dc03cf"
      url "https://github.com/akopichin/afm/releases/download/v#{version}/afm_linux_arm64.tar.gz"
    end
  end

  name "afm"
  desc "AI flow manager — orchestrates multi-stage agent runs"
  homepage "https://github.com/akopichin/afm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "afm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/afm"]
      system_command "/usr/bin/codesign", args: ["-f", "-s", "-", "#{staged_path}/afm"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Claude-скиллы (/afm, /afm-check и др.) не устанавливаются автоматически.
    Установить: afm install-skills
  EOS
end
