# This file was generated by GoReleaser. DO NOT EDIT.
cask "afm" do
  version "1.1.23"

  on_macos do
    on_intel do
      sha256 "3870007aaa23481f879a19f5bf65f57234e9f9ca535b80ae7fadda70fba26658"
      url "https://github.com/akopichin/afm/releases/download/v#{version}/afm_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "92ac8089d4c2d9c5b79a2317a8e0b0c624d0c8bf8fc0ff25c0dfe5587e7c163d"
      url "https://github.com/akopichin/afm/releases/download/v#{version}/afm_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e3cbd7f07d265b97cc52aaf5c22ebf77968b90fbacb9ad8c868319062ea603ca"
      url "https://github.com/akopichin/afm/releases/download/v#{version}/afm_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2a469623717875fac538be3ea5ae7f724574bc5adbc2186fe63e3e50be66a4d7"
      url "https://github.com/akopichin/afm/releases/download/v#{version}/afm_linux_arm64.tar.gz"
    end
  end

  name "afm"
  desc "AI flow manager — orchestrates multi-stage agent runs"
  homepage "https://github.com/akopichin/afm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "afm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/afm"]
      system_command "/usr/bin/codesign", args: ["-f", "-s", "-", "#{staged_path}/afm"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Claude-скиллы (/afm, /afm-check и др.) не устанавливаются автоматически.
    Установить: afm install-skills
  EOS
end
