# This file was generated by GoReleaser. DO NOT EDIT.
cask "afm" do
  version "0.5.8"

  on_macos do
    on_intel do
      sha256 "0e142aa531c6998ddbd7334d89c8a571f681fe0a7f7d130d3907d83a5d13ed2b"
      url "https://github.com/akopichin/afm/releases/download/v#{version}/afm_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e0c01691979af67f19015b667bb78908719a3f900d02e7797242950534be6258"
      url "https://github.com/akopichin/afm/releases/download/v#{version}/afm_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ef9bb8059aaeaee57678106973f47429c14830918491c665a957761e7151b668"
      url "https://github.com/akopichin/afm/releases/download/v#{version}/afm_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b55718b5c0f0dd47457fd2566e039bae759d77ffaa24d96cbac30120669205a0"
      url "https://github.com/akopichin/afm/releases/download/v#{version}/afm_linux_arm64.tar.gz"
    end
  end

  name "afm"
  desc "AI flow manager — orchestrates multi-stage agent runs"
  homepage "https://github.com/akopichin/afm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "afm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/afm"]
      system_command "/usr/bin/codesign", args: ["-f", "-s", "-", "#{staged_path}/afm"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Claude-скиллы (/afm, /afm-check и др.) не устанавливаются автоматически.
    Установить: afm install-skills
  EOS
end
